// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "73d718d70adf1ef2fe233fe1d28cf3f2a0a870339428f7ca79be004a79177551"
