// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "96c46c8c9afc6ecc0eb359fb3b47e17572e737829c55f0118540ccb394f8441e"
