// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "f73877e70e3bcb36bf0016dad928c6816f28089339c9c48638a1554d3922b9dc"
