// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "38bdfe373fe718b27917bb5b5dc3b56e9d23393dc945fcaf7a7b2560be740ac9"
