// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "a49446aa39697b1ecdfc17eb772facb2a8027197ed0ae44e1d27aa2fcaae8fa3"
