// Code generated by gen.go. DO NOT EDIT.

//go:build !ebitenexternaldll
// +build !ebitenexternaldll

package glfw

const glfwDLLHash = "7ab862be476df5b708ddcb98369ff882e5b987f31d8aabca822d1a3b47471877"
